### ISSUE TITLE
Include a documentation example that shows how to define from-until

### ISSUE THREAD

**Issue by gajus** [sass-mq/sass-mq#58]
I am assuming it is:

```scss
@include mq($from: a, $until: b) {

}
```

A documentation example would avoid the confusion. Generally speaking, [@include-media](http://include-media.com/) is more intuitive.

**Comment by kaelig** [comment]
Thanks, this is a very valid point and I had never looked at the documentation from the perspective of somebody who sees it for the first time.

I've added an example in the introduction, does this help?

See https://github.com/sass-mq/sass-mq/blob/who-uses-sass-mq/README.md

**Comment by gajus** [comment]
It does make more sense. The other thing thats not obvious is how to define whether lower/upper boundary is inclusive or exclusive.

**Comment by kaelig** [comment]
> Generally speaking, @include-media is more intuitive.

I really like @eduardoboucas's work and I too think include-media is very intuitive.

Sass MQ takes a slightly different path by solving a few problems out of the box:

- Include-media is very permissive. It's easy to get overlapping media queries when using `>=` and `<=` operators. Sass MQ makes the choice of having exclusive upper boundaries, so that developers can't accidentally mess up. e.g. you can't have two rules `(min-width: 600px)` and `(max-width: 600px)` triggering styles at the same time. In Sass MQ, `(max-width: 600px)` becomes `(max-width: 599px)` - in ems).
- Sass MQ provides a way to serve a fallback for IE8 that doesn't support IE8, which might or might not be a feature that you need, but some companies such as the BBC and the Guardian definitely do.

> The other thing thats not obvious is how to define whether lower/upper boundary is inclusive or exclusive.

Thanks, that's very good feedback. I've updated the example with an output to show the way Sass MQ compiles strict upper boundaries.

See https://github.com/sass-mq/sass-mq/blob/who-uses-sass-mq/README.md

Does that make more sense?

**Comment by gajus** [comment]
> Sass MQ provides a way to serve a fallback for IE8 that doesn't support IE8, which might or might not be a feature that you need, but some companies such as the BBC and the Guardian definitely do.

This shouldn't be a concern of sass-mq. It should be left to https://github.com/scottjehl/Respond and other polyfills of the kind.

> Include-media is very permissive. It's easy to get overlapping media queries when using >= and <= operators. Sass MQ makes the choice of having exclusive upper boundaries, so that developers can't accidentally mess up. e.g. you can't have two rules (min-width: 600px) and (max-width: 600px) triggering styles at the same time. In Sass MQ, (max-width: 600px) becomes (max-width: 599px) - in ems).

To an extent, this makes sense. However, this shouldn't be a concern of sass-mq either. There can be an additional abstraction or set of keywords that would enforce such a convention. Though limiting the entire API is not practical.

I am glad that you have reminded me this, though. I have been thinking about the best convention to proceed with. I like the @include-media API, but it is not going to fix the actual issue that I am having (overlapping breakpoints). Which brings me back to consider using "names" to define collections of media queries, e.g. (conceptual example)

```scss
$breakpoints: (
    mobile: '(max-width: 319px)',
    tablet: '(min-width: 320px) and (max-width: 599px)',
    desktop: '(min-width: 600px)'
);

@include media('mobile,tablet,desktop') {}
@include media('mobile,desktop') {}
@include media('tablet') {}
```

which should produce

```css
@media (max-width: 319px), (min-width: 320px) and (max-width: 599px), (min-width: 600px) {}
@media (max-width: 319px), (min-width: 600px) {}
@media (min-width: 320px) and (max-width: 599px) {}
```

If such were the implementation, then the only place where you need to make sure that there are no overlapping queries is the `$breakpoints` definition.

What would be the downsides/limitations of such a simple implementation as opposed using to sass-mq or include-media?

**Comment by eduardoboucas** [comment]
Sorry for hijacking the thread, but @kaelig mentioned me and I started following the discussion.

> I like the @include-media API, but it is not going to fix the actual issue that I am having (overlapping breakpoints)

What is the issue that you're having exactly?

As for the comparison between Sass MQ and include-media, @kaelig is right, they're two very different approaches. include-media was an attempt at a simpler syntax, but it's not as comprehensive as Sass MQ is, and probably never will be — a good example of that is precisely the fallback support for older browsers.
