### ISSUE TITLE
What future for Sass MQ?

### ISSUE THREAD

**Issue by kaelig** [sass-mq/sass-mq#84]
## Observations
- [Custom media queries](https://drafts.csswg.org/mediaqueries-4/#custom-mq) are around the corner.
- Sass 4.0 will [support the future Media Query syntax](https://github.com/sass/sass/issues/1864).
- IE8 is disappearing, making Sass MQ's [Responsive Mode: Off](https://github.com/sass-mq/sass-mq#responsive-mode-off) less and less useful.
- There are new features in Media Queries Level 4 (hover, pointer, color…), although the real-life use-cases are still limited
## Examples

This is how Sass MQ compares with the new up-and-coming features of Sass and Media Queries Level 4.
### Sass MQ

``` scss
@include mq($from: mobile, $until: tablet) { /* ... */ }
```
### Media Queries level 4

Note: you'd use PostCSS to compile this code to standard Media Queries.

``` scss
// New syntax
@media (width >= 20em) and (width < 46.24em) { /* ... */ }

// Custom Media Query - Example 1
@custom-media --from-mobile-until-tablet (width >= 20em) and (width < 46.24em);
@media (--from-mobile-until-tablet) { /* ... */ }

// Custom Media Query - Example 2
@custom-media --from-mobile (width >= 20em);
@custom-media --until-tablet (width < 46.24em);
@media (--from-mobile) and (--until-tablet) { /* ... */ }
```
### Sass 4.0

Sass should transpiled this code to a "standard" Media Query syntax.

``` scss
$mobile: 20em;
$tablet: 46.24em;
@media (width >= $mobile) and (width < $tablet) { /* ... */ }
```
## Questions
- What can we learn from this that could benefit Sass MQ?
- Is Sass MQ still going to be helpful? (which brings the question: Should Sass MQ still exist?)
- Can Sass MQ be an inspiration for the specification? What do you like in Sass MQ that you'd like to see in the spec?
- Should Sass MQ support more media query types?
  - What would the API look like?
  - What best practices would it promote (knowing there are only very few use cases outside of 'screen width/height' in RWD right now)?
- Should Sass MQ drop support for the non-responsive mode (mostly useful for IE8)? Note that this is achievable using [postcss-unmq](https://github.com/jonathantneal/postcss-unmq).

I'd love to hear your thoughts, as I'd like Sass MQ to be as relevant as possible in the future, unless it is better replaced by other tools (in which case there is no point supporting it).

**Comment by slavanga** [comment]
I think Sass MQ will still be relevant because we won't get these benefits from Media Queries level 4 or the Sass 4.0 syntax:
* automatic unit conversion
* compact and minimal syntax
* mobile first behavior as default

Dropping support for the non-responsive mode is a good idea. I have never used it in a real project.

**Comment by fvsch** [comment]
I’d remove the non-responsive mode, because it gets less and less useful (and people who need it can keep using the current sass-mq or use a specialized tool). You’ll get a leaner codebase and less features to focus on. But of course if there are no other updates planned, it might not be worth the trouble.

By the way, custom media queries were pushed out of Media Queries 4, and moved to “maybe for Media Queries 5”, if I’m reading the csswg GitHub logs well. So around the corner might be a bit of a stretch.

**Comment by coffeeneed** [comment]
Is sass-mq dead?

**Comment by kaelig** [comment]
@coffeeneed sass-mq is alive and well. It will get keep getting updates for new versions of Sass.

**Comment by kaelig** [comment]
Closing this in case it raises concerns about the future of sass-mq.
